// <auto-generated />
namespace HLL.HLX.BE.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20160519_Init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20160519_Init));
        
        string IMigrationMetadata.Id
        {
            get { return "201605190703030_20160519_Init"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
