// <auto-generated />
namespace HLL.HLX.BE.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Init_20160322 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init_20160322));
        
        string IMigrationMetadata.Id
        {
            get { return "201603220824588_Init_20160322"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
